version: '3'

services:
  web:
    image: gisu1102/2025techer:web
    container_name: django_web_prod
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/app/static
    expose:
      - "8000"

  nginx:
    image: gisu1102/2025techer:nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: