version: "3.9"
services:
  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - django-network

  redis:
    image: redis:alpine
    container_name: redis_service
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - django-network
      
  # Celery 워커
  celery:
    container_name: celery_worker
    build: .
    command: celery -A myCelery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - web
      - redis
    networks:
      - django-network

  # Celery Beat (주기적 작업 실행)
  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A myCelery beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq
      - celery
    networks:
      - django-network

  # RabbitMQ 서비스
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_USER : linkin
      RABBITMQ_PASSWORD : linkin    
    ports:
      - "15672:15672"  # RabbitMQ 웹 UI (관리 페이지)
      - "5672:5672"    # RabbitMQ 브로커 포트
    networks:
      - django-network

  # OpenSearch 서비스
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Link-in1234

    ports:
      - "9200:9200" 
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - django-network

  # OpenSearch 대시보드
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    networks:
      - django-network

  # Logstash
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # 로컬에 저장한 django 로그를 logstash에 전달하기 위한 볼륨 매핑
      - ./django_logs:/usr/share/logstash/logs
    networks:
      - django-network

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
      # docker에서 실행되는 django의 로그를 로컬에 저장하기 위한 볼륨 매핑
      - ./django_logs:/app/django_logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
      - opensearch
    networks:
      - django-network

volumes:
  db_data:
  opensearch_data:

networks:
  django-network:
    driver: bridge