version: "3.9"
services:
  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - django-network

  redis:
    image: redis:alpine
    container_name: redis_service
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - django-network
      
  # Celery 워커
  celery:
    container_name: celery_worker
    build: .
    command: celery -A myCelery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - web
      - redis
    networks:
      - django-network

  # Celery Beat (주기적 작업 실행)
  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A myCelery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
      - celery
    networks:
      - django-network

  # RabbitMQ 서비스
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_USER : linkin
      RABBITMQ_PASSWORD : linkin    
    ports:
      - "15672:15672"  # RabbitMQ 웹 UI (관리 페이지)
      - "5672:5672"    # RabbitMQ 브로커 포트
    networks:
      - django-network

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - django-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
    networks:
      - django-network

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - django-network

volumes:
  db_data:
  opensearch_data:

networks:
  django-network:
    driver: bridge