# Generated by Django 3.2.25 on 2025-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('memo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
