# Generated by Django 3.2.25 on 2025-01-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='node_id',
        ),
        migrations.AddField(
            model_name='memo',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='node.node'),
            preserve_default=False,
        ),
    ]
