# Generated by Django 4.2.18 on 2025-01-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='node_id',
            new_name='node',
        ),
    ]
