# Generated by Django 3.2.25 on 2025-01-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noderelation',
            old_name='from_node',
            new_name='from_node_id',
        ),
        migrations.RenameField(
            model_name='noderelation',
            old_name='to_node',
            new_name='to_node_id',
        ),
        migrations.RenameField(
            model_name='noderelation',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='relationtype',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='usernoderelation',
            old_name='node',
            new_name='node_id',
        ),
        migrations.RenameField(
            model_name='usernoderelation',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='usernodetotype',
            old_name='relation_type',
            new_name='relation_type_id',
        ),
        migrations.RenameField(
            model_name='usernodetotype',
            old_name='user_node',
            new_name='user_node_id',
        ),
    ]
