# Generated by Django 4.2.18 on 2025-01-26 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('node', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernoderelation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationtotype',
            name='node_relation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.noderelation'),
        ),
        migrations.AddField(
            model_name='relationtotype',
            name='relation_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.relationtype'),
        ),
        migrations.AddField(
            model_name='noderelation',
            name='from_node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='node.node'),
        ),
        migrations.AddField(
            model_name='noderelation',
            name='to_node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='node.node'),
        ),
        migrations.AddField(
            model_name='noderelation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
