# Generated by Django 3.2.25 on 2025-01-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20250117_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernoderelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
