# Generated by Django 4.2.18 on 2025-01-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='user',
            new_name='user_id',
        ),
    ]
