# Generated by Django 4.2.18 on 2025-01-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_node_node_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
