# Generated by Django 4.2.18 on 2025-01-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_node_node_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_img',
            field=models.ImageField(blank=True, null=True, upload_to='node_images/'),
        ),
    ]
